<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'PrettyLinks\\chillerlan\\Settings\\' => array($vendorDir . '/chillerlan/php-settings-container/src'),
    'PrettyLinks\\chillerlan\\QRCode\\' => array($vendorDir . '/chillerlan/php-qrcode/src'),
    'PrettyLinks\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'PrettyLinks\\GroundLevel\\Support\\' => array($vendorDir . '/caseproof/ground-level-support'),
    'PrettyLinks\\GroundLevel\\Resque\\' => array($vendorDir . '/caseproof/ground-level-resque'),
    'PrettyLinks\\GroundLevel\\QueryBuilder\\' => array($vendorDir . '/caseproof/ground-level-query-builder'),
    'PrettyLinks\\GroundLevel\\Package\\' => array($vendorDir . '/caseproof/ground-level-package'),
    'PrettyLinks\\GroundLevel\\Mothership\\' => array($vendorDir . '/caseproof/ground-level-mothership'),
    'PrettyLinks\\GroundLevel\\InProductNotifications\\' => array($vendorDir . '/caseproof/ground-level-in-product-notifications'),
    'PrettyLinks\\GroundLevel\\Events\\' => array($vendorDir . '/caseproof/ground-level-events'),
    'PrettyLinks\\GroundLevel\\Database\\' => array($vendorDir . '/caseproof/ground-level-database'),
    'PrettyLinks\\GroundLevel\\Container\\' => array($vendorDir . '/caseproof/ground-level-container'),
    'PrettyLinks\\DeviceDetector\\' => array($vendorDir . '/matomo/device-detector'),
    'PrettyLinks\\Caseproof\\GrowthTools\\' => array($vendorDir . '/caseproof/growth-tools/src'),
    'PrettyLinks\\' => array($baseDir . '/src'),
);
